apiVersion: v1
kind: Service
metadata:
  name: blog-api
  labels:
    test: test
    labele2: label
spec:
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: blog-api
  sessionAffinity: None
  type: ClusterIP